"""DESIGN DEBT REPORT — PRODUCT POLISH SPRINT
Generated by audit of all 6 UI screens, 376-line styles.py, 603-line ui_components.py,
search.py (450 lines), search_intelligence.py (514 lines), live_inference.py (126 lines)
"""

DESIGN_DEBT = """
P0 — MUST FIX (Blocking polish feel)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. No loading/skeleton states anywhere
   - Screens go blank → full render → content appears
   - Need skeleton placeholders for search results, metric panels
   - Pages: all 3 search pages + about/overview

2. No unified spacing scale
   - Ad-hoc values: 0.3rem, 0.4rem, 0.6rem, 0.65rem, 0.75rem, 0.85rem mixed
   - No consistent 4/8/12/16/24/32/48 rhythm
   - Pages: styles.py line 46-376, every component uses arbitrary numbers

3. information_panel class missing from CSS
   - ui_components.py line 370-375 renders information-panel div
   - No .information-panel class exists in styles.py → unstyled fallback
   - Affects: live_inference.py cold-start warning, every page using it

4. EMOJI icons instead of SVG
   - All type icons, status icons, search result icons are emoji
   - Unprofessional appearance at large sizes
   - Pages: search.py _type_icon() (7 emoji), ui_components.py SuggestedQuery icons

5. Inline evolution CSS in Python file
   - 40 lines of CSS injected via st.markdown in search_intelligence.py lines 322-362
   - Should be in styles.py for maintainability
   - Page: Version Evolution tab

6. Result cards lack visual hierarchy
   - Inline styles in search.py lines 266-281
   - No elevation, no proper spacing, score and path look cluttered
   - Page: Search Workspace results

P1 — SHOULD FIX (Noticeable polish gaps)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

7. No keyboard focus ring for custom elements
   - Only .search-page has :focus-visible in styles.py line 79-80
   - Metric cards, health cards, pipeline stages have no focus indication
   - Accessibility gap

8. Missing dark mode for several component variants
   - badge classes missing dark overrides
   - health-dot colors not adapted
   - evo-node-dot classes not adapted for dark mode

9. No transition on sidebar navigation
   - Page changes are instant cut, no fade or slide
   - Feels abrupt

10. Search Health metric cards no tooltips
    - Users can't see what gate threshold means without reading table below
    - Metric-card could have hover tooltip

11. Version Evolution expandable details are plain markdown
    - Just raw **V0 — Baseline** text, no visual node detail panel
    - Missing the "expandable node details" requirement

12. Live Inference health cards without icon
    - Cards are plain text with dot indicator
    - Could use subtle SVG badge for each parameter type

13. Search type filter uses selectbox instead of pill buttons
    - selectbox with 9 options feels heavy
    - Pill/chip filter would be more Vercel-style

14. No search timing indicator on results
    - Users can't tell how fast search was
    - Line 434-436 just shows st.caption with index stats, no query timing

P2 — NICE TO HAVE (Future polish)

15. Empty states are all identical centered text
    - No illustration, no icon, no suggestion for next action
    - All use the same .empty-state class

16. Pipeline arrows disappear on mobile (pipeline-arrow: display:none)
    - Using ::after content instead, which is fragile
    - Should use proper flex with visible arrows

17. Safe-table row stripe missing
    - .safe-table tbody tr hover works, but no alternating row color
    - Reduces scanability on wide tables

18. Sidebar has no micro-interaction on hover
    - select/radio items just change color instantly
    - No subtle scale or background shift

19. No transition when metric values change
    - Evaluation results appear instantly
    - No number-animation or fade-in for new data

20. Colab/GitHub link buttons use st.link_button (streamlit-native)
    - Inconsistent with custom styled action buttons
    - Not aligned with product design system
"""

print(DESIGN_DEBT)
